In [26]:
import pandas as pd
import numpy as np

df = pd.DataFrame([
    [1,2,3],
    [4,None,6],
    [7,8,None]],
    columns=list('ABC')
)

df

   A    B    C
0  1  2.0  3.0
1  4  NaN  6.0
2  7  8.0  NaN

In [27]:
df_1 = df.fillna({'C':100})
df_1

   A    B      C
0  1  2.0    3.0
1  4  NaN    6.0
2  7  8.0  100.0

In [28]:
df_2 = df.copy()
df_2['C'] = df_2['C'].fillna(100)
df_2

   A    B      C
0  1  2.0    3.0
1  4  NaN    6.0
2  7  8.0  100.0

In [18]:
# 이렇게 하면 바보됨.
df_3 = df['C'].fillna(100)
df_3

0      3.0
1      6.0
2    100.0
Name: C, dtype: float64

### 시험문제에서 종종 결측치를 제외하고 평균값을 구해서 그 값으로 결측치를 대치하라는 문제가 나온다
- 그런데, 평균값 계산할때 pandas 는 결측치를 제외하고 평균값을 계산한다.
- 따라서 아래 첫번째와 두번째 계산은 같은 값을 출력한다.
- (주의) 다른 컬럼에도 결측치가 있다면 세번째 계산과 같이 평균값이 달라지므로 주의한다.

In [ ]:
print(df)
B_mean_1 = df.B.dropna().mean()
B_mean_2 = df.B.mean()
B_mean_3 = df.dropna()['B'].mean()
print(B_mean_1, B_mean_2)
print(B_mean_3)

   A    B    C
0  1  2.0  3.0
1  4  NaN  6.0
2  7  8.0  NaN
5.0 5.0
2.0